### ISSUE TITLE
Build Failure due to Wrong Target Platform .asmdef file

### ISSUE THREAD

**Issue by EmreBeratKR** [bilalemregrkn/MyGrid#1]
# The Issue
- The assembly definition file's target platform is set as "Any Platform" at the path "Packages/MyGrid/Editor/bilalemregrkn.mygrid.Editor.asmdef". 
It should have set to "Editor" checked only. And it causes build errors.

- To fix it, simply set its target platform to "Editor" checked only.

# Issue Screenshots
- **[BROKEN]** Packages/MyGrid/Editor/bilalemregrkn.mygrid.Editor.asmdef

![wrong_asmdef](https://user-images.githubusercontent.com/87636497/232231432-a066208c-7fcd-4d83-a57c-89968cfd2c72.png)

- Build Error logs

![log](https://user-images.githubusercontent.com/87636497/232231470-c3caddc5-768c-46ab-b617-51671ac6a4c8.png)

# Fix Screenshot

- **[FIXED]** Packages/MyGrid/Editor/bilalemregrkn.mygrid.Editor.asmdef

![correct_asmdef](https://user-images.githubusercontent.com/87636497/232232072-f86d0442-0639-454a-ab12-1bfa136fb82b.png)

**Comment by bilalemregrkn** [comment]
Thanks a lot! ❤️

**Comment by bilalemregrkn** [comment]
Fixed bug!

**Comment by EmreBeratKR** [comment]
You are welcome 😃
